# Generated by Django 2.2.28 on 2023-03-29 11:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='releaseDate',
            field=models.DateField(blank=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 3, 29))]),
        ),
    ]
